name: Bindings

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: Generate contracts Go bindings
        run: (cd ./contracts && make)
 